"""make taste nullable

Revision ID: 0a9b19810d4e
Revises: 329a6bc2f023
Create Date: 2026-06-13 11:31:10.592031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a9b19810d4e'
down_revision: Union[str, Sequence[str], None] = '329a6bc2f023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shots', schema=None) as batch_op:
        batch_op.alter_column('taste',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shots', schema=None) as batch_op:
        batch_op.alter_column('taste',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
