"""initial tables

Revision ID: 98553ef6c6e0
Revises: 
Create Date: 2026-06-12 20:08:30.295563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98553ef6c6e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('product', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'product', name='uq_bean_identity')
    )
    op.create_table('grinders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('scale_type', sa.String(length=20), nullable=False),
    sa.Column('step_native', sa.Float(), nullable=False),
    sa.Column('finer_is_lower', sa.Boolean(), nullable=False),
    sa.Column('snap', sa.Float(), nullable=False),
    sa.Column('min_native', sa.Float(), nullable=True),
    sa.Column('max_native', sa.Float(), nullable=True),
    sa.Column('unit_label', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bean_id', sa.Integer(), nullable=False),
    sa.Column('grinder_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('grind_setting_native', sa.String(length=30), nullable=False),
    sa.Column('dose_g', sa.Float(), nullable=False),
    sa.Column('yield_g', sa.Float(), nullable=False),
    sa.Column('time_s', sa.Float(), nullable=False),
    sa.Column('taste', sa.String(length=20), nullable=False),
    sa.Column('intensity', sa.String(length=10), nullable=True),
    sa.Column('reason_code', sa.String(length=50), nullable=False),
    sa.Column('roast_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bean_id'], ['beans.id'], ),
    sa.ForeignKeyConstraint(['grinder_id'], ['grinders.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shots')
    op.drop_table('machines')
    op.drop_table('grinders')
    op.drop_table('beans')
    # ### end Alembic commands ###
